package test;

import org.apache.commons.io.IOUtils;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.net.URLDecoder;
import java.net.URLEncoder;
import java.util.ArrayList;
import java.util.List;

public class TestConvert {
    public static void main(String[] args) throws Exception {
        List<String> lines = IOUtils.readLines(new FileInputStream("D:\\temp\\ccc\\all.csv"), "UTF-8");
        System.out.println(lines.size());

        //String curl = "curl 'http://10.15.166.222/cis-web//cis/preQueryProduct/callQuery' -H 'Pragma: no-cache' -H 'Origin: http://10.15.166.222' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: zh-CN,zh;q=0.9' -H 'User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36' -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' -H 'Accept: application/json, text/javascript, */*; q=0.01' -H 'Cache-Control: no-cache' -H 'X-Requested-With: XMLHttpRequest' -H 'Cookie: ares.session.id=c2190608-e987-4e9e-beb3-9a04bd9db6c9' -H 'Connection: keep-alive' -H 'Referer: http://10.15.166.222/cis-web/cis/preQueryProduct/page' --data 'creditOrgCode=td&productCode=preLoanAntifraud&custName=李冬瑞&idType=I&idNo=411381198706078212&mobile=18321832693&bizOrgUserNo=TL&reason=&operatorId=&queryParam.bankNo=&queryParam.mail=&queryParam.address=&queryParam.ip=&queryParam.mac=&queryParam.wifiMac=&queryParam.imei=&queryParam.loanTerm=&queryParam.loanTermUnit=MONTH&queryParam.loanDate=&queryParam.loanAmount=&queryParam.loanAmountRange=&queryParam.beginScanTime=&queryParam.endScanTime=&queryParam.scanPeriod=&queryParam.queryDate=&queryParam.offset=&queryParam.size=&queryParam.mail=&queryParam.linkman_Cll=&queryParam.contacts_name=&queryParam.relationship=&queryParam.applId=&queryParam.userIdType=&queryParam.token=&queryParam.userId=&queryParam.channelID=&queryParam.userCardRecordID=&queryParam.black_box=&queryParam.app_name=&queryParam.token_id=&queryParam.biz_code=&%E6%8F%90%E4%BA%A4=' --compressed";

        //String curl = "curl 'http://10.15.166.222/cis-web//cis/preQueryProduct/callQuery' -H 'Pragma: no-cache' -H 'Origin: http://10.15.166.222' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: zh-CN,zh;q=0.9' -H 'User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36' -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' -H 'Accept: application/json, text/javascript, */*; q=0.01' -H 'Cache-Control: no-cache' -H 'X-Requested-With: XMLHttpRequest' -H 'Cookie: ares.session.id=c2190608-e987-4e9e-beb3-9a04bd9db6c9' -H 'Connection: keep-alive' -H 'Referer: http://10.15.166.222/cis-web/cis/preQueryProduct/page' --data 'creditOrgCode=za&productCode=zaRiskRank&custName=李冬瑞&idType=I&idNo=350626198802290015&mobile=18621366401&bizOrgUserNo=TL&reason=&operatorId=&queryParam.bankNo=&queryParam.mail=&queryParam.address=&queryParam.ip=&queryParam.mac=&queryParam.wifiMac=&queryParam.imei=&queryParam.loanTerm=&queryParam.loanTermUnit=MONTH&queryParam.loanDate=&queryParam.loanAmount=&queryParam.loanAmountRange=&queryParam.beginScanTime=&queryParam.endScanTime=&queryParam.scanPeriod=&queryParam.queryDate=&queryParam.offset=&queryParam.size=&queryParam.mail=&queryParam.linkman_Cll=&queryParam.contacts_name=&queryParam.relationship=&queryParam.applId=&queryParam.userIdType=&queryParam.token=&queryParam.userId=&queryParam.channelID=&queryParam.userCardRecordID=&queryParam.black_box=&queryParam.app_name=&queryParam.token_id=&queryParam.biz_code=&%E6%8F%90%E4%BA%A4=&%E6%8F%90%E4%BA%A4=' --compressed";

        //String curl = "curl 'http://10.15.166.222/cis-web//cis/preQueryProduct/callQuery' -H 'Pragma: no-cache' -H 'Origin: http://10.15.166.222' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: zh-CN,zh;q=0.9' -H 'User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36' -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' -H 'Accept: application/json, text/javascript, */*; q=0.01' -H 'Cache-Control: no-cache' -H 'X-Requested-With: XMLHttpRequest' -H 'Cookie: ares.session.id=ff6cde47-b652-4c47-b978-58552d7de3e8' -H 'Connection: keep-alive' -H 'Referer: http://10.15.166.222/cis-web/cis/preQueryProduct/page' --data 'creditOrgCode=td&productCode=preLoanAntifraud&custName=%E8%83%A1%E6%99%93%E7%90%9B&idType=I&idNo=310105199004041215&mobile=15921544146&bizOrgUserNo=TL&reason=&operatorId=&queryParam.bankNo=&queryParam.mail=&queryParam.address=&queryParam.ip=&queryParam.mac=&queryParam.wifiMac=&queryParam.imei=&queryParam.loanTerm=&queryParam.loanTermUnit=MONTH&queryParam.loanDate=&queryParam.loanAmount=&queryParam.loanAmountRange=&queryParam.beginScanTime=&queryParam.endScanTime=&queryParam.scanPeriod=&queryParam.queryDate=&queryParam.offset=&queryParam.size=&queryParam.mail=&queryParam.linkman_Cll=&queryParam.contacts_name=&queryParam.relationship=&queryParam.applId=&queryParam.userIdType=&queryParam.token=&queryParam.userId=&queryParam.channelID=&queryParam.userCardRecordID=&queryParam.black_box=&queryParam.app_name=&queryParam.token_id=&queryParam.biz_code=&%E6%8F%90%E4%BA%A4=&%E6%8F%90%E4%BA%A4=' --compressed";
        //String curl = "curl 'http://10.15.166.222/cis-web//cis/preQueryProduct/callQuery' -H 'Pragma: no-cache' -H 'Origin: http://10.15.166.222' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: zh-CN,zh;q=0.9' -H 'User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36' -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' -H 'Accept: application/json, text/javascript, */*; q=0.01' -H 'Cache-Control: no-cache' -H 'X-Requested-With: XMLHttpRequest' -H 'Cookie: ares.session.id=ff6cde47-b652-4c47-b978-58552d7de3e8' -H 'Connection: keep-alive' -H 'Referer: http://10.15.166.222/cis-web/cis/preQueryProduct/page' --data 'creditOrgCode=za&productCode=zaRiskRank&custName=%E8%83%A1%E6%99%93%E7%90%9B&idType=I&idNo=310105199004041215&mobile=15921544146&bizOrgUserNo=TL&reason=&operatorId=&queryParam.bankNo=&queryParam.mail=&queryParam.address=&queryParam.ip=&queryParam.mac=&queryParam.wifiMac=&queryParam.imei=&queryParam.loanTerm=&queryParam.loanTermUnit=MONTH&queryParam.loanDate=&queryParam.loanAmount=&queryParam.loanAmountRange=&queryParam.beginScanTime=&queryParam.endScanTime=&queryParam.scanPeriod=&queryParam.queryDate=&queryParam.offset=&queryParam.size=&queryParam.mail=&queryParam.linkman_Cll=&queryParam.contacts_name=&queryParam.relationship=&queryParam.applId=&queryParam.userIdType=&queryParam.token=&queryParam.userId=&queryParam.channelID=&queryParam.userCardRecordID=&queryParam.black_box=&queryParam.app_name=&queryParam.token_id=&queryParam.biz_code=&%E6%8F%90%E4%BA%A4=&%E6%8F%90%E4%BA%A4=' --compressed";

        String curl= "curl 'http://10.15.166.222/cis-web//cis/preQueryProduct/callQuery' -H 'Pragma: no-cache' -H 'Origin: http://10.15.166.222' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: zh-CN,zh;q=0.9' -H 'User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36' -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' -H 'Accept: application/json, text/javascript, */*; q=0.01' -H 'Cache-Control: no-cache' -H 'X-Requested-With: XMLHttpRequest' -H 'Cookie: ares.session.id=4c882d7a-b976-4e13-a286-a54da3a6e007' -H 'Connection: keep-alive' -H 'Referer: http://10.15.166.222/cis-web/cis/preQueryProduct/page' --data 'creditOrgCode=jxl&productCode=jxlHoneyPot&custName=%E8%83%A1%E6%99%93%E7%90%9B&idType=I&idNo=310105199004041215&mobile=15921544146&bizOrgUserNo=TL&reason=&operatorId=&queryParam.bankNo=&queryParam.mail=&queryParam.address=&queryParam.ip=&queryParam.mac=&queryParam.wifiMac=&queryParam.imei=&queryParam.loanTerm=&queryParam.loanTermUnit=MONTH&queryParam.loanDate=&queryParam.loanAmount=&queryParam.loanAmountRange=&queryParam.beginScanTime=&queryParam.endScanTime=&queryParam.scanPeriod=&queryParam.queryDate=&queryParam.offset=&queryParam.size=&queryParam.mail=&queryParam.linkman_Cll=&queryParam.contacts_name=&queryParam.relationship=&queryParam.applId=&queryParam.userIdType=&queryParam.token=&queryParam.userId=&queryParam.channelID=&queryParam.userCardRecordID=&queryParam.black_box=&queryParam.app_name=&queryParam.token_id=&queryParam.biz_code=&queryParam.openID=&queryParam.custID=&queryParam.uid=&%E6%8F%90%E4%BA%A4=' --compressed";

        List<String> converted = new ArrayList<>();
        for (String line : lines) {
            String[] columns = line.split(",");
            String new_curl = curl;
            String name = columns[0].replace("\"", "");
//            name = URLEncoder.encode(name, "UTF-8");
            new_curl = new_curl.replaceAll("%E8%83%A1%E6%99%93%E7%90%9B", name);
            new_curl = new_curl.replaceAll("310105199004041215", columns[1]);
            new_curl = new_curl.replaceAll("15921544146", columns[2]);
            converted.add(new_curl);
            //System.out.println(new_curl);
        }

        FileWriter writer = new FileWriter("D:\\temp\\ccc\\curls-all.txt");
        IOUtils.writeLines(converted, "\r\r\r", writer);
        writer.close();
    }
}
